### ISSUE TITLE
Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by EasternSunShadow** [abhinavs/cookie#1]
Hi there, thanks for your contribution of this beautiful theme. 

After I  ran `bin/bootstrap` success , and then `bin/start`,
Then I met a problem log like this:
```
192:cookie-master xxx$ bin/start
Configuration file: /Users/xxx/cookie-master/_config.yml
module.js:491
    throw err;
    ^
Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Library/Ruby/Gems/2.6.0/gems/jekyll-postcss-0.4.0/bin/postcss:3:33)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
```

Did I miss something or did something wrong?
If so, please give me some advice.

You can get some detail in my published [Github Page](https://easternsunshadow.github.io)

**Comment by abhinavs** [comment]
Sorry, I missed this issue.

Can you please see
1. If node and npm were installed
2. Were there any errors when you ran bin/bootstrap?

**Comment by abhinavs** [comment]
Closing it because of inactivity.
