### ISSUE TITLE
Cannot serve on cloud Google Drive folder

### ISSUE THREAD

**Issue by iokarkan** [abhinavs/cookie#11]
Hi! First of all, let me congratulate you on your theme, it looks amazing.

I want to study the theme, so I cloned it on my Google Drive shared folder, where I have also done some limited testing of other themes and jekyll in general.

I am using:
- mac OS 13.1
- and
```bash
/opt/homebrew/opt/ruby/bin/ruby
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
/usr/local/bin/jekyll
jekyll 4.3.1
```

The commands given in the readme replicate the error (anonymised user-specific fields):

```bash
./bin/bootstrap
./bin/start
```

and the error is the following
```bash
(base) ➜  cookie git:(master) ✗ ./bin/start                                 
Configuration file: /Users/***/Library/CloudStorage/GoogleDrive-*****@gmail.com/Other computers/My Laptop/***/***/cookie/_config.yml
            Source: /Users/***/Library/CloudStorage/GoogleDrive-*****@gmail.com/Other computers/My Laptop/***/***/cookie
       Destination: /Users/***/Library/CloudStorage/GoogleDrive-*****@gmail.com/Other computers/My Laptop/***/***/cookie/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
bundler: failed to load command: jekyll (/opt/homebrew/lib/ruby/gems/3.2.0/bin/jekyll)
/opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-postcss-v2-1.0.1/lib/jekyll-postcss-v2/hook.rb:32:in ``': No such file or directory - /Users/***/Library/CloudStorage/GoogleDrive-*****@gmail.com/Other (Errno::ENOENT)
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-postcss-v2-1.0.1/lib/jekyll-postcss-v2/hook.rb:32:in `process'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-postcss-v2-1.0.1/lib/jekyll-postcss-v2/hook.rb:42:in `block in <top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/hooks.rb:103:in `block in trigger'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/hooks.rb:102:in `each'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/hooks.rb:102:in `trigger'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:184:in `write'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:231:in `block in write'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:368:in `block (2 levels) in each_site_file'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:365:in `each'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:365:in `block in each_site_file'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:364:in `each'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:364:in `each_site_file'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:230:in `write'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:82:in `process'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.2.0/bin/jekyll:25:in `load'
        from /opt/homebrew/lib/ruby/gems/3.2.0/bin/jekyll:25:in `<top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
        from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
        from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
```

Let me know if there's anything else I can give to replicate the issue. Finally, no Google Drive is not full :P

*Edit: I should mention that I tried the same in a local folder and it works without this error, and the site loads.*

**Comment by abhinavs** [comment]
I apologize that I missed noticing this issue. Let me know if you are still seeing this issue. At my end too, I will check this in a couple of days.

Thank you.

**Comment by uc-Pri** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
AcidBurn18, @edgelesslab, @OldZealand03, @shazinahmed, @rhinetime, @thun88, @NeelDigonto, @Algernon-dev, @pranavarora1895, @paumnc, @dwvicy, @LJD0, @karasakalmt, @stevenroh, @Raikio, @crotestnet, @Koifshhh, @mucadoo, @cofin, @kejianlin
